name: medify
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.7
  flutter_screenutil: ^5.9.0
  adaptive_theme: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/bold/
    - assets/translations/
    - assets/svg/auth_svg/
    - assets/svg/broken/
    - assets/svg/bulk/
    - assets/svg/curved/
    - assets/svg/lightBorder/
    - assets/svg/lightOutline/
    - assets/svg/twoTone/
    - assets/svg/others/
    - assets/images/
    - assets/images/mood/
    - assets/fonts/
    - assets/lottie/
    - assets/styles/
    - assets/places/
    - assets/svg/additional_icons/
    - assets/images/fake_images/
    - assets/images/map_types/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist/Urbanist-Black.ttf
        - asset: assets/fonts/Urbanist/Urbanist-BlackItalic.ttf
        - asset: assets/fonts/Urbanist/Urbanist-Bold.ttf
        - asset: assets/fonts/Urbanist/Urbanist-BoldItalic.ttf
        - asset: assets/fonts/Urbanist/Urbanist-Italic.ttf
        - asset: assets/fonts/Urbanist/Urbanist-Medium.ttf
        - asset: assets/fonts/Urbanist/Urbanist-MediumItalic.ttf
        - asset: assets/fonts/Urbanist/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist/Urbanist-SemiBold.ttf
        - asset: assets/fonts/Urbanist/Urbanist-SemiBoldItalic.ttf
        - asset: assets/fonts/Urbanist/Urbanist-Thin.ttf
        - asset: assets/fonts/Urbanist/Urbanist-ThinItalic.ttf
          style: italic
    - family: Chakra
      fonts:
        - asset: assets/fonts/Chakra/ChakraPetch-Bold.ttf
        - asset: assets/fonts/Chakra/ChakraPetch-BoldItalic.ttf
        - asset: assets/fonts/Chakra/ChakraPetch-Italic.ttf
        - asset: assets/fonts/Chakra/ChakraPetch-Light.ttf
        - asset: assets/fonts/Chakra/ChakraPetch-LightItalic.ttf
        - asset: assets/fonts/Chakra/ChakraPetch-Medium.ttf
        - asset: assets/fonts/Chakra/ChakraPetch-MediumItalic.ttf
        - asset: assets/fonts/Chakra/ChakraPetch-Regular.ttf
        - asset: assets/fonts/Chakra/ChakraPetch-SemiBold.ttf
        - asset: assets/fonts/Chakra/ChakraPetch-SemiBoldItalic.ttf
          style: italic
